Server
ArkhamX2/studenda-server pull request #30
Opened 2023-08-21 20:13 UTC by S1stemus

Create Authorization

2023-08-24 20:25 UTC, dubstepTractor requested changes

2023-08-24 20:25 UTC, dubstepTractor commented on Studenda.Core.Server/Extension/JWT-Extension.cs
> +
лишняя строка

2023-08-24 20:25 UTC, dubstepTractor commented on Studenda.Core.Server/Extension/JWT-Extension.cs
> +
да в принципе можно просто запустить рефакторинг в иде и он должен поправить все подобные болячки.

2023-08-24 20:25 UTC, dubstepTractor commented on Studenda.Core.Server/Extension/JWT-Extension.cs
> +                expires: DateTime.Now.AddMinutes(tokenValidityInMinutes),
с этим нужно аккуратно очень работать, чтобы не ломать голову в будущем.

2023-08-24 20:25 UTC, dubstepTractor commented on Studenda.Core.Server/Program.cs
необходимо поправить кодировку.

2023-08-24 20:25 UTC, dubstepTractor commented on Studenda.Core.Server/Program.cs
> +app.UseCors("cors");
не пойму зачем нам корс?

2023-08-24 20:25 UTC, dubstepTractor commented on Studenda.Core.Server/Studenda.Core.Server.csproj
> +		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.4" />
поправить табуляцию.

2023-08-24 20:25 UTC, dubstepTractor commented on Studenda.Core.Server/utils/AuthOptions.cs
> +        const string KEY = "mysupersecret_secretkey!123";   // ключ для шифрации
ключ не должен быть в гит никогда. необходимо найти варианты использования ключа либо в настройках (при условии что они не попадут в гит), либо через переменные окружения. переменные предпочтительнее всего, тк их можно без проблем прокинуть в контейнер при деплое.

2023-08-24 20:25 UTC, dubstepTractor commented on Studenda.Core.Server/utils/Token/TokenModel.cs
> +    public class TokenModel
это не совсем модель насколько я понимаю.

2023-08-24 20:25 UTC, dubstepTractor commented on Studenda.Core.Server/utils/Token/TokenService.cs
> +    public class TokenService:ITokenService
пробела не хватает.

2023-08-24 20:25 UTC, dubstepTractor commented on Studenda.Core.Server/utils/loginRequest.cs
> +    public class loginRequest
классы должны именоваться с верхнего регистра: `LoginRequest`.

2023-08-24 20:25 UTC, dubstepTractor commented on Studenda.Core.Server/utils/loginRequest.cs
> +﻿namespace Studenda.Core.Server.utils
Пространства имен должны именоваться с верхнего регистра: `Studenda.Core.Server.Utils`.

2023-08-24 20:25 UTC, dubstepTractor commented on Studenda.Core.Server/utils/loginResponse.cs
> +    public class loginResponse
`LoginResponse`

2023-08-24 20:25 UTC, dubstepTractor commented on Studenda.Core.Server/utils/registerRequest.cs
> +    public class registerRequest
`RegisterRequest`

2023-08-24 20:25 UTC, dubstepTractor commented on Studenda.Core.Server/utils/registerResponse.cs
> +    public class registerResponse
`RegisterResponse`

2023-08-25 02:26 UTC, S1stemus commented on Studenda.Core.Server/utils/AuthOptions.cs
> +        const string KEY = "mysupersecret_secretkey!123";   // ключ для шифрации
Ты уже говорил, но пока не будет такой реализации пусть будет здесь

2023-08-25 02:30 UTC, S1stemus commented on Studenda.Core.Server/Extension/JWT-Extension.cs
> +                expires: DateTime.Now.AddMinutes(tokenValidityInMinutes),
уже поменял на UtcNow

2023-08-31 06:21 UTC, N0tilT commented
@dubstepTractor  @S1stemus Решите конфликты и мерджите, если всё ок. Нужно добавлять связь между сервером и моделью, клиентом

2023-09-02 18:49 UTC, dubstepTractor approved these changes

2023-09-04 20:18 UTC, merged